### ISSUE TITLE
Coverage exclude generated code

### ISSUE THREAD

**Issue by pjljvandelaar** [haskell/rfcs#21]
Many classes are not completely defined by the user.
For example a class can be defined using `deriving (Eq, Ord, Read, Show, Generic, NFData, Data)`.

Many users use coverage to determine the quality of their test set.
They aim for a high coverage number.

In Haskell 2010, when a class is defined using deriving, one has to write test code to cover the Top Level Definitions in the generated code.

Could Haskell 2020 make a distinction between user code and generate code, such that coverage only includes user code?

**Comment by cartazio** [comment]
this is a bug / feature request for ghc, not for language standard. 

(we are only going to consider stuff thats mature in at least one or more haskell implementations, ie ghc :) )
