### ISSUE TITLE
Avoid dependencies on GPL on all platforms

### ISSUE THREAD

**Issue by torxakis-admin** [haskell/rfcs#24]
Currently Haskell depends on package with GPL licenses, like integer-gmp.
On some platforms this results in license issues.
I would strongly recommend only using licenses like BSD3 and MIT
such that Haskell 2020 and the product derive with it can be easily used on ALL platforms.

**Comment by severen** [comment]
Isn't this an issue that is entirely unrelated to the Haskell *standard*, and therefore not fitting for this repository? Haskell-the-standard doesn't depend on anything GPL, it's just an abstract description of a programming language.

**Comment by cartazio** [comment]
agreed.

@torxakis-admin we welcome  you to contribute to ghc and other implementations if you care about this. But as otherwise stated, a specification isn't the place for license issues around linker dependencies to matter.
